version: '3.8'
services:
  main:
    image: myenv
    build: .
    runtime: nvidia
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: ["python", "main.py"]

  jupyter:
    image: myenv
    build: .
    runtime: nvidia
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]

